language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - pypy

before_install:
    - pip install --quiet coverage

install:
    - python setup.py install

script:
    - make test
    - coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
    - coverage report --show-missing
